import cubeNear from "./cube_near.mp4";
import cubeNearVP9 from "./cube_near_vp9.mp4";
import cubeSide from "./cube_side.mp4";
import cubeSideVP9 from "./cube_side_vp9.mp4";
export { default as curveWaves } from "./curve-waves.mp4";
export { default as loopWavy } from "./loop-wavy.mp4";
export { default as lotOfWavesBlack } from "./lot-of-waves-black.mp4";
export { default as rareWavesBlack } from "./rare-waves-black.mp4";
export { default as whiteWavesIdle } from "./white-waves-idle.mp4";
export { default as twistedTunel } from "./twisted-tunel.mp4";
export { default as abstractLoopBgWithLines } from "./abstract-loop-background-with-lines.mp4";
export { cubeNear, cubeNearVP9, cubeSide, cubeSideVP9 };
