export enum ApiPath {
  partner = "/partners",
  project = "/projects",
  projectDomain = "/project-domains",
  technology = "/technologies",
  comment = "/comments",
  contactUs = "/contact-uses",
  vacancyReplay = "/vacancy-replays",
  upload = "/upload",
  step = "/steps",
  service = "/services",
  worker = "/workers",
  vacancy = "/vacancies",
  whoWeAre = "/who-we-ares",
  insight = "/insights",
  insightCategory = "/insight-categories",
  subscribeNews = "/news-subscribers",
}
