name: Deploy to Cloudflare Pages

on:
  push:
    branches: ['production']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run build:prod:cloudflare

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'dist' #output directory
        env:
          PUBLIC_CMS_KEY: ${{ secrets.PUBLIC_CMS_KEY }}
          PIRIVATE_CMS_KEY: ${{ secrets.PIRIVATE_CMS_KEY }}
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
          PUBLIC_IMG_URL: ${{ secrets.PUBLIC_IMG_URL }}
